{
  "WombatDynamoUINodes.BuildingPadTypes, WombatDynamoUINodes": {
    "nodeType": "ExtensionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamoUINodes.RailingTypes, WombatDynamoUINodes": {
    "nodeType": "ExtensionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamoUINodes.RoofTypes, WombatDynamoUINodes": {
    "nodeType": "ExtensionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "Railing.Railing.ByPathTypeAndLevel@Autodesk.DesignScript.Geometry.PolyCurve,Railing.RailingType,Revit.Elements.Level": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "Railing.RailingType.Name": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "Railing.RailingType.ByName@string": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "Roof.FootPrintRoof.ByFootprint@Autodesk.DesignScript.Geometry.PolyCurve,Revit.Elements.Level,Revit.Elements.RoofType": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "Roof.FootPrintRoof.ByEdgesAndSlopes@Autodesk.DesignScript.Geometry.Line[],double[],Revit.Elements.Level,Revit.Elements.RoofType": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "Roof.ExtrusionRoof.ByProfile@Autodesk.DesignScript.Geometry.PolyCurve,Revit.Elements.ReferencePlane,Revit.Elements.Level,Revit.Elements.RoofType,double,double": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "BuildingPad.BuildingPad.ByOutlinesTypeAndLevel@Autodesk.DesignScript.Geometry.Curve[],BuildingPad.BuildingPadType,Revit.Elements.Level": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "BuildingPad.BuildingPad.ByOutlineTypeAndLevel@Autodesk.DesignScript.Geometry.PolyCurve,BuildingPad.BuildingPadType,Revit.Elements.Level": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "BuildingPad.BuildingPadType.Name": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "BuildingPad.BuildingPadType.ByName@string": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Area.ByAreaPlanAndPoint@Revit.Elements.Element,Autodesk.DesignScript.Geometry.Point": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.AreaBoundaryLine.ByCurveAndView@Autodesk.DesignScript.Geometry.Curve,Revit.Elements.Element": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.AreaPlanView.ByLevel@Revit.Elements.Level": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.AreaPlanView.ByLevelAndSchemeName@Revit.Elements.Level,string": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.BoundingBox.Evaluate@Autodesk.DesignScript.Geometry.BoundingBox,double,double,double": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.BoundingBox.Dimensions@Autodesk.DesignScript.Geometry.BoundingBox": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Column.IsSlanted@Revit.Elements.Element": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Column.CoordinateSystem@Revit.Elements.Element": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.CurtainGrid.ByWall@Revit.Elements.Wall": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.CurtainGrid.AddGridLine@WombatDynamo.CurtainGrid,Autodesk.DesignScript.Geometry.Point[],bool,bool,bool": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.CurtainGrid.GetPanels@WombatDynamo.CurtainGrid": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Curve.SmartOffset@Autodesk.DesignScript.Geometry.Curve,double": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Plane.Deconstruct@Autodesk.DesignScript.Geometry.Plane": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Point.Deconstruct@Autodesk.DesignScript.Geometry.Point": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Vector.Deconstruct@Autodesk.DesignScript.Geometry.Vector": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Element.SetParameterValuesByNames@Revit.Elements.Element,string[],var[]": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Element.Unpin@Revit.Elements.Element": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Element.GetType@Revit.Elements.Element": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Element.FilterByType@Revit.Elements.Element[],Revit.Elements.Element": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Element.FilterByParameterValue@Revit.Elements.Element[],string,var": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Element.TryGetPropertyValue@Revit.Elements.Element,string": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Element.GetPropertyNames@Revit.Elements.Element": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Element.ById@int": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.FamilyInstance.SetType@Revit.Elements.FamilyInstance,Revit.Elements.FamilyType": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.FamilyInstance.Flip@Revit.Elements.FamilyInstance,bool,bool": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.FamilyInstance.IsInPlace@Revit.Elements.FamilyInstance": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.FamilyInstance.Orientation@Revit.Elements.FamilyInstance": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.FamilyInstance.ByPointHostTypeAndLevel@Autodesk.DesignScript.Geometry.Point,Revit.Elements.Element,Revit.Elements.FamilyType,Revit.Elements.Level": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.IO.ExportAsDWG@string,string,Revit.Elements.Element[]": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.IO.ExportAsFBX@string,string,Revit.Elements.Views.View3D": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Level.ByName@string": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.List.NullItem": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.List.Wrap@var[]": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.List.Unwrap@WombatDynamo.List_Wrapper": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.List.NullToEmptyList@var[]": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.List.FilterByName@var[],string": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Opening.ByPathTypeAndLevel@Autodesk.DesignScript.Geometry.PolyCurve,Revit.Elements.Level,Revit.Elements.Level": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Polyline.Vertices": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Polyline.Count": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Polyline.ByPolyCurve@Autodesk.DesignScript.Geometry.PolyCurve": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Polyline.ToPolyCurve": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Polyline.ByPoints@Autodesk.DesignScript.Geometry.Point[]": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Polyline.Reduce@WombatDynamo.Polyline,double": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Polyline.ClosestPoint@Autodesk.DesignScript.Geometry.Point": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Workset.Name": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Workset.Id": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Workset.InfoFromElement@Revit.Elements.Element": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Workset.IdFromName@string": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Workset.NameFromId@int": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Workset.ByName@string": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Workset.AssignToElement@WombatDynamo.Workset,Revit.Elements.Element": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Workset.SelectAll": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.String.Format@string,var": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Wall.AllowDisallowJoins@Revit.Elements.Wall,bool": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Wall.ByCurveAndLocation@Autodesk.DesignScript.Geometry.Curve,double,Revit.Elements.Level,Revit.Elements.WallType,string,bool": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Wall.InsertDoorOrWindow@Revit.Elements.Wall,Autodesk.DesignScript.Geometry.Point,Revit.Elements.FamilyType,Revit.Elements.Level": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  },
  "WombatDynamo.Wall.ByProfile@Autodesk.DesignScript.Geometry.Curve[],Revit.Elements.WallType,Revit.Elements.Level,double": {
    "nodeType": "FunctionNode",
    "packageName": "WombatDynamo",
    "packageVersion": "2.3.5"
  }
}
